version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=web_mysqli
      - BASE_URL=http://localhost:8080
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - diamond-store-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=web_mysqli
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./web_mysqli.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - diamond-store-network

volumes:
  mysql-data:


networks:
  diamond-store-network:
    driver: bridge
